# Generated by Django 4.0.1 on 2022-10-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewguide', '0006_rename_location_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='brewguide.location'),
        ),
    ]
