# Generated by Django 4.0.1 on 2022-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewguide', '0007_alter_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=54.34996656351821, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='long',
            field=models.DecimalField(decimal_places=6, default=-6.26895114106519, max_digits=9),
            preserve_default=False,
        ),
    ]
