# Generated by Django 4.0.1 on 2022-10-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewguide', '0008_shop_lat_shop_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
            preserve_default=False,
        ),
    ]
