# Generated by Django 4.0.1 on 2022-10-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewguide', '0009_shop_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brewguide')),
            ],
        ),
    ]
