# Generated by Django 4.0.1 on 2022-10-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewguide', '0010_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
